
name: build-tools

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  info:
    runs-on: ubuntu-24.04
    outputs:
      BUILD_DATE: ${{ steps.info.outputs.BUILD_DATE }}
    steps:
      - name: Get Latest Commit Id
        id: info
        run: |
          echo BUILD_DATE=`date +'%Y-%m-%d'` >> ${GITHUB_OUTPUT}

  build-windows:
    runs-on: windows-2022
    needs: info
    env:
      BUILD_DATE: ${{ needs.info.outputs.BUILD_DATE }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Build Script
        id: build
        shell: cmd
        run: call build.bat

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tools-win-${{ needs.info.outputs.BUILD_DATE }}
          path: tools-win-${{ needs.info.outputs.BUILD_DATE }}.zip
          if-no-files-found: error
          compression-level: 0

  build-mac:
    runs-on: macos-latest
    needs: info
    env:
      BUILD_DATE: ${{ needs.info.outputs.BUILD_DATE }}
    steps:

      - name: Update XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Build Script
        id: build
        shell: bash
        run: bash build.sh mac

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tools-mac-${{ needs.info.outputs.BUILD_DATE }}
          path: tools-mac-${{ needs.info.outputs.BUILD_DATE }}.zip
          if-no-files-found: error
          compression-level: 0

  release:
    runs-on: ubuntu-24.04
    needs: [info, build-windows, build-mac]
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:

      - name: Create GitHub Release
        run: |
          echo 'tools' >> notes.txt
          echo 'build date: ${{ needs.info.outputs.BUILD_DATE }}'
          gh release create ${{ needs.info.outputs.BUILD_DATE }} -R "${GITHUB_REPOSITORY}" -t '${{ needs.info.outputs.BUILD_DATE }}' -F notes.txt

      - name: Get Artifacts From Build Steps
        uses: actions/download-artifact@v4
        with:
          pattern: tools-*-${{ needs.info.outputs.BUILD_DATE }}
          merge-multiple: true

      - name: Upload Artifacts to GitHub Release
        run: gh release upload '${{ needs.info.outputs.BUILD_DATE }}' tools-*.zip -R "${GITHUB_REPOSITORY}"
